# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5dc723dfec8f2d62af5120a7e05db979e4bb43e9e47d5ad7b6c4b445fddbedebf1452346b1974c37fd8ad0de6ba5bef3114b6402afd1cdda0878bbfbe7ba80f1

test:
  secret_key_base: ecf2378f335c16754c7a1032d8d6a95b325d4e67ef349895ae4b259bf45c3478b7147ac8e93ff084c7318574a06f515be6eef86f43f20681b66a859272528051

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
